ARG BASE_ARCH_SUFFIX=
FROM ghcr.io/quasarnova-team/quasar-ci:alma10-o6${BASE_ARCH_SUFFIX} AS build
WORKDIR /src
COPY . .
COPY demo/Design.xml Design/Design.xml
COPY demo/config.xml bin/config.xml
COPY demo/QuasarServer.cpp Server/src/QuasarServer.cpp
RUN ./quasar.py enable_module open62541-compat v1.5.8 \
 && ./quasar.py set_build_config open62541_config.cmake \
 && ./quasar.py generate device --all \
 && ./quasar.py build Release \
 && cp -rL build/bin /out \
 && cp build/Configuration/Configuration.xsd /out-Configuration.xsd

FROM almalinux:10
RUN dnf install -y epel-release \
 && dnf install -y boost xerces-c openssl-libs \
 && dnf clean all
WORKDIR /server
COPY --from=build /out/ .
COPY --from=build /out-Configuration.xsd /Configuration/Configuration.xsd
COPY demo/Design.xml /demo/Design.xml
EXPOSE 4841
ENTRYPOINT ["./OpcUaServer"]
